apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: rabbitmq-server-scaling-demo-hpa
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: worker
  minReplicas: 1
  maxReplicas: 50
  metrics:
  - type: Object
    object:
      metric:
        name: rabbitmq_queue_messages
        selector: {matchLabels: {queue: tasks_queue}}
        metricSelector:
          matchLabels:
            resource.labels.forwarding_rule_name: k8s-fw-default-basic-ingress--ffd629d77b6630de
      describedObject:
        apiVersion: "/v1"
        kind: Service
        name: rabbitmq-server-scaling-demo
      target:
        type: Value
        value: 100
