prometheus-node-exporter:
# Mount the node's root file system (/) at /host/root in the container
  hostRootFsMount:
    enabled: false
      # Defines how new mounts in existing mounts on the node or in the container
      # are propagated to the container or node, respectively. Possible values are
      # None, HostToContainer, and Bidirectional. If this field is omitted, then
      # None is used. More information on:
      # https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation
    mountPropagation: HostToContainer
