apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq-sample
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rabbitmq-sample
    spec:
      containers:
        - name:  worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "worker"
