prometheus:
  url: http://prometheus-scaling-demo-server.rabbitmq-scaling-demo.svc.cluster.local
  port: 80

rbac:
  create: true

serviceAccount:
  create: true

service:
  port: 443

logLevel: 6
rules:
  default: false
  custom:
  - seriesQuery: 'rabbitmq_queue_messages{}'
    resources:
      overrides:
       # needed to change this, or kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1/ wouldn't return anything:
       # https://github.com/kubernetes-sigs/prometheus-adapter/issues/548
       namespace: {resource: "namespace"}
       pod: {resource: "pod"}
    metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>)